name = "uptax-bolt"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./build/client"

# Environment variables can be added here
[vars]
NODE_VERSION = "20.17.0"
