#:schema node_modules/wrangler/config-schema.json
name = "uptax-bolt"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"
pages_build_output_dir = "./build/client"
send_metrics = false

# Environment variables can be added here
[vars]
NODE_VERSION = "20.17.0"
